comments:
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: true
    searchInProtectedClass: true
  UndocumentedPublicFunction:
    active: true
    searchProtectedFunction: true
  UndocumentedPublicProperty:
    active: true
    searchProtectedProperty: true

complexity:
  ComplexCondition:
    active: false
  CyclomaticComplexMethod:
    active: false
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    threshold: 3
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  TooManyFunctions:
    active: false

coroutines:
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true

exceptions:
  ObjectExtendsThrowable:
    active: true
  ThrowingExceptionInMain:
    active: true

naming:
  BooleanPropertyNaming:
    active: true
  LambdaParameterNaming:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true

performance:
  UnnecessaryPartOfBinaryExpression:
    active: true

potential-bugs:
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  ExitOutsideMain:
    active: true
  IgnoredReturnValue:
    restrictToConfig: false
  ImplicitUnitReturnType:
    active: true
    allowExplicitReturnType: true
  LateinitUsage:
    active: true
  MissingPackageDeclaration:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullCheck:
    active: true

style:
  active: true
  AlsoCouldBeApply:
    active: true
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  DestructuringDeclarationWithTooManyEntries:
    active: false
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExpressionBodySyntax:
    active: true
    includeLineWrapping: true
  ForbiddenComment:
    active: false
  ForbiddenMethodCall:
    active: true
  LoopWithTooManyJumpStatements:
    active: false
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  MultilineLambdaItParameter:
    active: true
  MultilineRawStringIndentation:
    active: true
    indentSize: 2
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  OptionalUnit:
    active: false
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    active: false
  TrailingWhitespace:
    active: true
  TrimMultilineRawString:
    active: true
  UnderscoresInNumericLiterals:
    active: true
    acceptableLength: 3
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
  WildcardImport:
    active: true # TODO: needed?
