build: {}

config: {}

processors:
  exclude: []

console-reports:
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
    # - 'LiteFindingsReport'

output-reports: {}

comments:
  UndocumentedPublicClass:
    searchInProtectedClass: true
  UndocumentedPublicFunction:
    searchProtectedFunction: true
  UndocumentedPublicProperty:
    searchProtectedProperty: true

complexity:
  # ComplexCondition:
  #   active: false
  # CyclomaticComplexMethod:
  #   active: false
  # LargeClass:
  #   active: false
  # LongMethod:
  #   active: false
  # LongParameterList:
  #   active: false
  # NestedBlockDepth:
  #   active: false
  StringLiteralDuplication:
    excludeStringsWithLessThan5Characters: false
  # TooManyFunctions:
  #   active: false

coroutines: {}

empty-blocks: {}

exceptions:
  SwallowedException:
    ignoredExceptionTypes: []

naming: {}

performance: {}

potential-bugs:
  # TODO
  IgnoredReturnValue:
    restrictToConfig: false
  ImplicitUnitReturnType:
    allowExplicitReturnType: true

style:
  ExpressionBodySyntax:
    includeLineWrapping: true
  ForbiddenComment:
    active: false
  ForbiddenMethodCall:
    methods: []
  # LoopWithTooManyJumpStatements:
  #   active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
  MultilineRawStringIndentation:
    indentSize: 2
  # OptionalUnit:
  #   active: false
  # ReturnCount:
  #   active: false
  # ThrowsCount:
  #   active: false
  WildcardImport:
    active: true
    excludeImports: []
