build: {}

config: {}

processors:
  exclude: []

console-reports:
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
    # - 'LiteFindingsReport'

output-reports: {}

comments:
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    searchInProtectedClass: true
  UndocumentedPublicFunction:
    searchProtectedFunction: true
  UndocumentedPublicProperty:
    searchProtectedProperty: true

complexity:
  StringLiteralDuplication:
    excludeStringsWithLessThan5Characters: false

coroutines: {}

empty-blocks: {}

exceptions:
  SwallowedException:
    ignoredExceptionTypes: []

naming: {}

performance: {}

potential-bugs:
  IgnoredReturnValue:
    restrictToConfig: false
  ImplicitUnitReturnType:
    allowExplicitReturnType: true

style:
  ExpressionBodySyntax:
    includeLineWrapping: true
  ForbiddenComment:
    active: false
  ForbiddenMethodCall:
    methods: []
  MaxLineLength:
    maxLineLength: 100
  # Indentation rule not consistent with https://kotlinlang.org/docs/coding-conventions.html#strings
  MultilineRawStringIndentation:
    active: false
  OptionalUnit:
    active: false
  WildcardImport:
    active: true
    excludeImports: []
